#!/usr/bin/env python3
import json, os, pathlib, datetime, urllib.request, urllib.parse
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / 'inbox'
OUT.mkdir(exist_ok=True)
TOPIC = os.getenv('EVOLUTION_TOPIC', 'agent self improvement github actions verification')
QUERY = urllib.parse.quote(TOPIC + ' stars:>1000')
url = f'https://api.github.com/search/repositories?q={QUERY}&sort=stars&order=desc&per_page=5'
req = urllib.request.Request(url, headers={'Accept':'application/vnd.github+json','User-Agent':'hermes-evolver'})
if os.getenv('GITHUB_TOKEN'):
    req.add_header('Authorization', 'Bearer ' + os.getenv('GITHUB_TOKEN'))
with urllib.request.urlopen(req, timeout=30) as r:
    data = json.load(r)
items=[]
for repo in data.get('items',[])[:5]:
    items.append({
        'name': repo.get('full_name'),
        'url': repo.get('html_url'),
        'stars': repo.get('stargazers_count'),
        'description': repo.get('description'),
        'language': repo.get('language'),
        'updated_at': repo.get('updated_at')
    })
report = {
    'generated_at': datetime.datetime.utcnow().isoformat()+'Z',
    'topic': TOPIC,
    'mode': 'minimum_remote_loop_verification',
    'model_route': {
        'primary': 'gpt-5.5',
        'assistants': ['deepseek-v4-flash','MiniMax-M2.7-highspeed']
    },
    'repositories': items,
    'gene': {
        'name': 'github_remote_search_to_verified_inbox',
        'mechanism': 'use GitHub Actions container to search real repositories and write verifiable structured output back to inbox',
        'verification': 'output file generated by remote workflow from live GitHub API results',
        'boundary': 'this proves remote loop and data回流, not yet deep code absorption'
    }
}
out = OUT / ('evolution_result_' + datetime.datetime.utcnow().strftime('%Y%m%d_%H%M%S') + '.json')
out.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
print(out.name)
